In [1]:
import pandas as pd

# 2023 Data

In [2]:
# df = pd.read_csv('./raw/2024_submissions_static.csv')
df = pd.read_csv('./raw/2024_submissionsView_Will.csv')
df.rename(columns={'Title Policies & Services Volulme':'Title Policies & Services Volume',
                    '2024 avg home price':'Avg Home Price'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1506 entries, 0 to 1505
Data columns (total 25 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   CompanyID                               1506 non-null   object
 1   Company                                 1506 non-null   object
 2   2019 Volume                             1011 non-null   object
 3   2020 Volume                             1080 non-null   object
 4   2021 Volume                             1101 non-null   object
 5   2022 Volume                             1337 non-null   object
 6   2023 Volume                             1506 non-null   object
 7   2019 Sides                              1011 non-null   float64
 8   2020 Sides                              1080 non-null   float64
 9   2021 Sides                              1101 non-null   float64
 10  2022 Sides                              1337 non-null   float64
 11  2023 Sides                              1506 non-null   int64
 12  City                                    1506 non-null   object
 13  State                                   1506 non-null   object
 14  Country Code                            1506 non-null   object
 15  Referral Network                        1506 non-null   object
 16  Logo                                    1503 non-null   object
 17  Mortgage Loan Transactions              37 non-null     object
 18  Mortgage Loan Volume                    37 non-null     object
 19  Title Policies & Services Transactions  44 non-null     object
 20  Title Policies & Services Volume        40 non-null     object
 21  Home Warranty Policies Sold             21 non-null     object
 22  Homeowners Insurance Policies Sold      31 non-null     object
 23  Escrow Policies Sold                    25 non-null     object
 24  Avg Home Price                          1506 non-null   object
dtypes: float64(4), int64(1), object(20)
memory usage: 294.3+ KB

## 2023 Mortgages

In [3]:
mortgage = df.loc[~df['Mortgage Loan Transactions'].isnull(), ['CompanyID', 'Company', 'Mortgage Loan Transactions', 'Mortgage Loan Volume']].reset_index(drop=True)
# clean this: "30.35M (total transactions overall)"
mortgage.loc[mortgage['Mortgage Loan Volume']=='30.35M (total transactions overall)', 'Mortgage Loan Volume'] = str(30.35 * 1000000)
# clean punctuation
mortgage['Mortgage Loan Volume'] = [int(x.replace(',','').replace('.','').replace('$','')) for x in mortgage['Mortgage Loan Volume']]
mortgage['Mortgage Loan Transactions'] = [int(x.replace(',','').replace('.','').replace('$','')) for x in mortgage['Mortgage Loan Transactions']]
mortgage

,CompanyID,Company,Mortgage Loan Transactions,Mortgage Loan Volume
0,reczKnazN8kUWC7Ia,Seven Gables Real Estate,156,65500000
1,recv7rHCTFzGFuq4X,"Pinnacle Estate Properties, Inc",81,537000000
2,recYd3CVoXzCgVO58,Helen Adams Realty,92,149000000
3,recKPKgjX6JQbz3qK,The Keyes Company/Illustrated Properties,390,124719168
4,rec7KuhkLJHD7fZhW,Cutler Real Estate,337,87779192
5,recaw2ijvz7cQEjZK,The Group Inc. Real Estate Associates,393,170283560
6,recNQyP3VhQnyyLHW,RE/MAX Select Realty,85,18217427
7,recShAgvIUgbucJ3P,@Properties,4707,2301182594
8,recE8cogq3Qq3MbfX,Michael Saunders & Company,103,40574499
9,recDpzQMTZlVLU3AF,Carolina One Real Estate Services,437,139414552
10,recfIaMe2c3nA3VUu,"The Real Brokerage, Inc.",238,79736971
11,recofEf2Uvn2iqGJ0,Five Star Real Estate,15,4356714
12,rec8rtGLMkTHxY4He,HUNT Real Estate ERA & ERA Key Realty Services,1744,426967641
13,recSwGTLQvvxIWQRu,Corner House Realty,34,11639916
14,recVasXPL6zHeELWI,Madison & Company Properties LLC,51,23899283
15,recXwUt1EVWh1wAXd,Hanna Holdings Inc,6084,1448004553
16,rec37Nf0DXWL2zIPe,Realty Concepts,112,38786889
17,rec9FdKWlPikSqX7c,C3 Real Estate Solutions,29,16132814
18,reccoMROv3nnDd0Cj,Terrie O'Connor Realtors,23,9926829
19,rectWprZrnwysWo79,HomeServices of America,21271,6951339309
20,recAQgaKshVaADSQO,EXIT Results Realty,170,55000000
21,recfJeDgt96jJOws9,Radius,76,303500000
22,recnsbQUkM7fqsG2Q,Wallace Real Estate,175,52690325
23,recRTLsmLOia9EsNS,William Raveis,1525,766251704
24,recwSyoFJxCRJl7La,Ruhl&Ruhl Realtors,614,133359976
25,recA67XhWu9KnUO51,Real Estate One Family of Companies,1734,598000000
26,rech3TkIZ0BRC4eYj,"Baird & Warner Real Estate, Inc.",1226,375817572
27,recr0ORds3XtqaiDm,Crye-Leike Real Estate Services,1624,444900000
28,recAfTfuXZjIn8zZ8,Berkshire Hathaway HomeServices Homesale Realty,574,117700000
29,recLqJRvdTGNZz4p2,Coldwell Banker Howard Perry and Walston,248,68774425
30,recdI2ZyMdTdDCTjE,First Team Real Estate,21,13313967
31,rec29a5ryHxyfjr5m,RE/MAX Alliance,396,170000000
32,rec4i6lPbIGiASyPC,Watson Realty Corp.,285,84963235
33,recZoQzZkPvG9ybIK,"Sibcy Cline, Inc.",194,50217784
34,rec2eAquo54soIhE7,London Properties,78,24852000
35,rec4d2yVoDXlbQoH4,8z Real Estate,290,132720787
36,recR1FWrrs0H0672r,RE/MAX Signature,100,30000000

In [4]:
mortgage.to_excel('./cleaned/MortgageCos.xlsx', index=False)

## 2023 Title

In [5]:
titles = df.loc[~df['Title Policies & Services Transactions'].isnull(), ['CompanyID', 'Company', 'Title Policies & Services Transactions', 'Title Policies & Services Volume']].reset_index(drop=True)
titles['Title Policies & Services Volume'] = [float(str(x).replace('$','').replace(',','')) if x != '' else x for x in titles['Title Policies & Services Volume']]
titles['Title Policies & Services Transactions'] = titles['Title Policies & Services Transactions'].str.replace(',','').astype('int')
titles

,CompanyID,Company,Title Policies & Services Transactions,Title Policies & Services Volume
0,recn0HaY78aRYlVnf,"Stark Real Estate Operations, LLC",707,3.181734e+08
1,recv7rHCTFzGFuq4X,"Pinnacle Estate Properties, Inc",2189,5.694967e+06
2,recd08ciluNKrBgQO,The Signature Real Estate Companies,495,NaN
3,recYd3CVoXzCgVO58,Helen Adams Realty,4045,4.115536e+06
4,recKPKgjX6JQbz3qK,The Keyes Company/Illustrated Properties,1903,8.984137e+08
5,rec7KuhkLJHD7fZhW,Cutler Real Estate,984,2.868011e+08
6,recSDHAGpINE5zlGB,LAER Realty Partners,228,9.931000e+07
7,recatTuQjuR6jwN2T,Liz Moore & Associates,750,3.430000e+08
8,recNQyP3VhQnyyLHW,RE/MAX Select Realty,1282,3.252305e+08
9,recxhnPWZGlemMAIt,Premier Sotheby's International Realty (A Peer...,219,2.900000e+08
10,recShAgvIUgbucJ3P,@Properties,6333,3.596997e+09
11,recE8cogq3Qq3MbfX,Michael Saunders & Company,836,4.214826e+08
12,recDpzQMTZlVLU3AF,Carolina One Real Estate Services,1158,5.512080e+08
13,recQ0oYU2eit4fkBF,McColly Real Estate,2578,6.801208e+08
14,recfIaMe2c3nA3VUu,"The Real Brokerage, Inc.",964,2.943271e+06
15,recofEf2Uvn2iqGJ0,Five Star Real Estate,3148,5.177738e+06
16,rec8rtGLMkTHxY4He,HUNT Real Estate ERA & ERA Key Realty Services,3102,7.714631e+08
17,rec3i5RiG6rndopjI,Samson Properties,4729,2.128050e+09
18,recSostp44bFr6hIC,Janet McAfee Inc.,349,NaN
19,recSwGTLQvvxIWQRu,Corner House Realty,249,4.323624e+05
20,recVasXPL6zHeELWI,Madison & Company Properties LLC,41,3.121060e+07
21,recXwUt1EVWh1wAXd,Hanna Holdings Inc,16566,4.513980e+09
22,recZpiZw84Ktis2P7,Douglas Elliman,308,NaN
23,rec9FdKWlPikSqX7c,C3 Real Estate Solutions,157,9.828293e+07
24,reccoMROv3nnDd0Cj,Terrie O'Connor Realtors,192,9.847600e+07
25,receOapiZoNydj6Vx,DASH Carolina,757,5.868020e+05
26,rectWprZrnwysWo79,HomeServices of America,79835,NaN
27,recxiWzrUbTpyL3d9,Lohmiller Real Estate,94,NaN
28,recAQgaKshVaADSQO,EXIT Results Realty,295,NaN
29,recEKkbVPLwnZMy6K,"Coldwell Banker River Valley, Realtors",366,3.982360e+05
30,recEVsAF1GXTS4FA8,Realty Executives Arizona Territory,1265,2.875279e+06
31,reclSueTm96CQZEs7,Berkshire Hathaway HomeServices Michigan Real ...,7500,8.837612e+06
32,recRTLsmLOia9EsNS,William Raveis,489,4.011251e+08
33,recA67XhWu9KnUO51,Real Estate One Family of Companies,8100,2.720000e+09
34,rech3TkIZ0BRC4eYj,"Baird & Warner Real Estate, Inc.",5760,2.191865e+06
35,recr0ORds3XtqaiDm,Crye-Leike Real Estate Services,9070,2.303209e+09
36,recAfTfuXZjIn8zZ8,Berkshire Hathaway HomeServices Homesale Realty,3649,9.394758e+08
37,recLqJRvdTGNZz4p2,Coldwell Banker Howard Perry and Walston,2300,1.170422e+09
38,recdI2ZyMdTdDCTjE,First Team Real Estate,3851,4.790000e+09
39,rec4i6lPbIGiASyPC,Watson Realty Corp.,1938,6.627656e+08
40,recZoQzZkPvG9ybIK,"Sibcy Cline, Inc.",974,NaN
41,recJQMZy7jggpQ0mR,The Russell Realty Co,1525,8.446370e+05
42,recbUBQTEhvKNjc3g,Chinowth & Cohen,2346,4.035270e+08
43,recdltbf6X9WGyV01,Chase International,342,3.533860e+08

In [6]:
titles.to_excel('./cleaned/TitleCos.xlsx', index=False)

## 2023 Home Warranty

In [7]:
warranty = df.loc[~df['Home Warranty Policies Sold'].isnull(), ['CompanyID', 'Company', 'Home Warranty Policies Sold']].reset_index(drop=True)
# drop 'none' value
warranty = warranty.loc[warranty['Home Warranty Policies Sold']!='none']
warranty['Home Warranty Policies Sold'] = warranty['Home Warranty Policies Sold'].astype('int')
warranty.sort_values(by='Home Warranty Policies Sold', ascending=False, inplace=True)
warranty.reset_index(drop=True, inplace=True)
warranty

,CompanyID,Company,Home Warranty Policies Sold
0,rectWprZrnwysWo79,HomeServices of America,13539
1,recMmJQNYCm4qAjB6,Jason Mitchell Real Estate,1800
2,recoOjX7rPPUNShBi,Key Realty LTD,1202
3,recZoQzZkPvG9ybIK,"Sibcy Cline, Inc.",893
4,reczKnazN8kUWC7Ia,Seven Gables Real Estate,675
5,recr0ORds3XtqaiDm,Crye-Leike Real Estate Services,620
6,recAfTfuXZjIn8zZ8,Berkshire Hathaway HomeServices Homesale Realty,507
7,recnsbQUkM7fqsG2Q,Wallace Real Estate,480
8,recSHgjKjMujDwrsd,NorthGroup Real Estate,300
9,rec7KuhkLJHD7fZhW,Cutler Real Estate,277
10,recDpzQMTZlVLU3AF,Carolina One Real Estate Services,256
11,recn0HaY78aRYlVnf,"Stark Real Estate Operations, LLC",192
12,rec4i6lPbIGiASyPC,Watson Realty Corp.,189
13,recQ0oYU2eit4fkBF,McColly Real Estate,188
14,recxiWzrUbTpyL3d9,Lohmiller Real Estate,111
15,recHeHB9yxZudPmYr,"Cressy & Everett, Inc.",103
16,recEKkbVPLwnZMy6K,"Coldwell Banker River Valley, Realtors",52
17,recAz270EacnZmRyu,ERA Central Realty Group,45
18,recHObaNWBAld9A0G,"The Platinum Group, Realtors",44
19,recd08ciluNKrBgQO,The Signature Real Estate Companies,26

In [8]:
warranty.to_excel('./cleaned/WarrantyCos.xlsx', index=False)

## 2023 Escrow

In [9]:
escrow = df.loc[~df['Escrow Policies Sold'].isnull(), ['CompanyID', 'Company', 'Escrow Policies Sold']].reset_index(drop=True)
# drop Pamela
escrow = escrow.loc[escrow['Escrow Policies Sold']!='Pamela']
# drop nulls
escrow['Escrow Policies Sold'] = escrow['Escrow Policies Sold'].str.replace(',','').astype('int')
escrow = escrow.loc[escrow['Escrow Policies Sold']>0].sort_values(by='Escrow Policies Sold', ascending=False).reset_index(drop=True)
escrow

,CompanyID,Company,Escrow Policies Sold
0,rectWprZrnwysWo79,HomeServices of America,25595
1,rec3i5RiG6rndopjI,Samson Properties,4729
2,recofEf2Uvn2iqGJ0,Five Star Real Estate,3563
3,recLbGeTk8MjhEEa4,NP Dodge Real Estate,2614
4,recdI2ZyMdTdDCTjE,First Team Real Estate,2038
5,recv7rHCTFzGFuq4X,"Pinnacle Estate Properties, Inc",1734
6,recaw2ijvz7cQEjZK,The Group Inc. Real Estate Associates,1711
7,recZpiZw84Ktis2P7,Douglas Elliman,1439
8,recJQMZy7jggpQ0mR,The Russell Realty Co,1375
9,reczKnazN8kUWC7Ia,Seven Gables Real Estate,980
10,recfIaMe2c3nA3VUu,"The Real Brokerage, Inc.",964
11,rec4d2yVoDXlbQoH4,8z Real Estate,707
12,recoQkkECxZntS6VN,RE/MAX Big Bear/Area Experts,392
13,recdltbf6X9WGyV01,Chase International,342
14,recAQgaKshVaADSQO,EXIT Results Realty,295
15,recSwGTLQvvxIWQRu,Corner House Realty,249
16,recSostp44bFr6hIC,Janet McAfee Inc.,229
17,recQ82De9d3cLQioA,RE/MAX Connections,223
18,rec9FdKWlPikSqX7c,C3 Real Estate Solutions,157

In [10]:
escrow.to_excel('./cleaned/EscrowCos.xlsx', index=False)

## 2023 Brokers

In [11]:
df.drop(columns=[
    'Mortgage Loan Transactions', 'Mortgage Loan Volume',
    'Title Policies & Services Transactions', 'Title Policies & Services Volume',
    'Home Warranty Policies Sold',
    'Escrow Policies Sold',
    'Homeowners Insurance Policies Sold'
], inplace=True)

In [12]:
df.head(1).T

                                                                  0
CompanyID                                         reczKnazN8kUWC7Ia
Company                                    Seven Gables Real Estate
2019 Volume                                                     NaN
2020 Volume                                                     NaN
2021 Volume                                             $2513166869
2022 Volume                                          $2179788441.00
2023 Volume                                             $1709676747
2019 Sides                                                      NaN
2020 Sides                                                      NaN
2021 Sides                                                   3031.0
2022 Sides                                                   2433.0
2023 Sides                                                     2119
City                                                         Tustin
State                                                            CA
Country Code                                                     US
Referral Network                                          LeadingRE
Logo              7.png (https://v5.airtableusercontent.com/v3/u...
Avg Home Price                                              $806832

In [13]:
df['Avg Home Price'] = df['Avg Home Price'].str.replace(',','').str.replace('$','').astype('int')

for col in df.columns[(df.columns.str.contains('Volume'))]:
    df[col] = df[col].str.replace(',','').str.replace('$','').astype('float')
df.head()

,CompanyID,Company,2019 Volume,2020 Volume,2021 Volume,2022 Volume,2023 Volume,2019 Sides,2020 Sides,2021 Sides,2022 Sides,2023 Sides,City,State,Country Code,Referral Network,Logo,Avg Home Price
0,reczKnazN8kUWC7Ia,Seven Gables Real Estate,NaN,NaN,2.513167e+09,2.179788e+09,1.709677e+09,NaN,NaN,3031.0,2433.0,2119,Tustin,CA,US,LeadingRE,7.png (https://v5.airtableusercontent.com/v3/u...,806832
1,recn0HaY78aRYlVnf,"Stark Real Estate Operations, LLC",7.147031e+08,7.539407e+08,7.938111e+08,7.029704e+08,9.513262e+08,2469.0,2551.0,2371.0,1904.0,2203,Ficthburg,WI,US,LeadingRE,Stark_Logo__Real_People_Tagline.jpg (https://v...,431832
2,recR8yxovQcfGnqBc,Keller Williams Main Line,NaN,NaN,NaN,8.392892e+08,9.685138e+08,NaN,NaN,NaN,1925.0,2240,Ardmore,PA,US,Keller Williams,kellerwilliams_prim_logo_pms200.png (https://v...,432372
3,reccrsQM3YrT1nMgO,Keller Williams Success Realty,1.213888e+09,1.967353e+09,2.107071e+09,1.180615e+09,1.409216e+09,3856.0,5230.0,4472.0,2184.0,2737,South Ogden,UT,US,Keller Williams,kellerwilliams_prim_logo_pms200.png (https://v...,514876
4,recsWmbo7T6v00rYa,CENTURY 21 North East,1.232887e+09,1.283628e+09,1.682546e+09,1.594295e+09,2.176130e+09,3293.0,3105.0,3567.0,3277.0,5098,Peabody,MA,US,CENTURY 21,38V3SivORu6asYe0CMAi (https://v5.airtableuserc...,426860

In [14]:
df.to_excel('./cleaned/CleanedSubmissions.xlsx', index=False)